from errtoans import main

main('./example_test.py')
